### ISSUE TITLE
feat: add "thank u for using canvas-sync - star us on github" note after pull/update commands

### ISSUE THREAD

**Issue by aidanaden** [aidanaden/canvas-sync#95]
Add "thank u" message + "gl for school u gots dis" message after pull/update commands

them nus kids have it tough (i am them)

**Comment by 733amir** [comment]
@aidanaden Can I work with this issue?

**Comment by aidanaden** [comment]
> @aidanaden Can I work with this issue?

sure - i plan on adding some funny messages as well, will prolly do that in a separate PR

**Comment by 733amir** [comment]
I was thinking about adding the message as a `PostRun` function for each of the commands you said, or as a `PersistentPostRun` in `rootCmd`  so all commands print the message you want on a successful exit. What are your thoughts on that?

**Comment by aidanaden** [comment]
> I was thinking about adding the message as a `PostRun` function for each of the commands you said, or as a `PersistentPostRun` in `rootCmd` so all commands print the message you want on a successful exit. What are your thoughts on that?

having a function that runs after a command completes sounds like a good idea 👍  - i'm unsure if we should add it to `rootCmd` though, i think it's better to have granular control over which commands have the `thank u` message printed (might be spammy if every command prints it after completion)

**Comment by 733amir** [comment]
Is this what you have in mind?
<img width="808" alt="image" src="https://github.com/aidanaden/canvas-sync/assets/8651598/a380de9c-ae01-43a5-943a-a1621ba2594d">

**Comment by aidanaden** [comment]
> Is this what you have in mind? <img alt="image" width="808" src="https://user-images.githubusercontent.com/8651598/269653316-a380de9c-ae01-43a5-943a-a1621ba2594d.png">

yep! perhaps with an `info` instead - otherwise seems pretty good! btw how did u come across this repo? haha

**Comment by 733amir** [comment]
> yep! perhaps with an info instead - otherwise seems pretty good!

Can you take a look at #103 ?

> btw how did u come across this repo? haha

I was looking for repos with `good first issue` label to start my open source contribution journey and I found this issue on [goodfirstissues.com](https://goodfirstissues.com/)

**Comment by aidanaden** [comment]
closed in #103
